GET http://localhost:9099/getUser

####

POST http://localhost:9099/createUser
Content-Type: application/json

{
   "firstName": "franco",
   "lastName": "diberto",
   "email": "franco@diberto.com",
   "password": "password",
   "age":39
}

####

GET http://localhost:9099/getUser/65fc86e73955c26170600e0e

####

PATCH http://localhost:9099/updateUser/65fc86e73955c26170600e0e
Content-Type: application/json
{
    "lastName":"Franco",
    "email":"franco@diberto.com",
    "password":"password",
}

####

DELETE http://localhost:9099/deletetUser/65fc92ff88ba9fbef6567b13

####
GET http://localhost:9099/getUser/salvo