POST http://localhost:3030/books/create
Content-Type: application/json

{
  "title": "titolo del libro 5",
  "price": 299.99,
  "isFeatured": false,
  "author": "Marco",
  "description": "lorem ipsum dolor sit amet."
}

####
GET http://localhost:3030/books
